"""add is_tracked to assets

Revision ID: 1dfe6250fb11
Revises: 49c0938975cb
Create Date: 2026-08-01 23:27:30.761111

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1dfe6250fb11'
down_revision: Union[str, None] = '49c0938975cb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assets', sa.Column('is_tracked', sa.Boolean(), server_default='false', nullable=False), schema='market')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('assets', 'is_tracked', schema='market')
    # ### end Alembic commands ###
