"""drop dead snapshot allocation column

Revision ID: 49c0938975cb
Revises: c8d2e5a1f6b3
Create Date: 2026-07-30 21:47:33.938750

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '49c0938975cb'
down_revision: Union[str, None] = 'c8d2e5a1f6b3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('snapshots', 'allocation', schema='portfolio')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('snapshots', sa.Column('allocation', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True), schema='portfolio')
    # ### end Alembic commands ###
