"""add provider column to latest_quotes

Revision ID: 5f0cf3688bca
Revises: 8a09da24d2aa
Create Date: 2026-07-11 17:53:20.954042

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5f0cf3688bca'
down_revision: Union[str, None] = '8a09da24d2aa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('latest_quotes', sa.Column('provider', sa.String(), nullable=True), schema='market')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('latest_quotes', 'provider', schema='market')
    # ### end Alembic commands ###
