"""add is_archived to portfolios

Revision ID: 630dbcacdc95
Revises: 942dce1f19c8
Create Date: 2026-07-21 13:55:36.221516

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '630dbcacdc95'
down_revision: Union[str, None] = '942dce1f19c8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('portfolios', sa.Column('is_archived', sa.Boolean(), server_default=sa.text('false'), nullable=False), schema='portfolio')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('portfolios', 'is_archived', schema='portfolio')
    # ### end Alembic commands ###
