"""add margin_usd to positions

Revision ID: 682d73d52b1a
Revises: 93ce033de8cf
Create Date: 2026-07-16 14:50:23.521881

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '682d73d52b1a'
down_revision: Union[str, None] = '93ce033de8cf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('positions', sa.Column('margin_usd', sa.Numeric(), nullable=True), schema='portfolio')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('positions', 'margin_usd', schema='portfolio')
    # ### end Alembic commands ###
