"""P1 Strategic Indexes

Revision ID: 762c07784edc
Revises: 7aa59fe7bbf8
Create Date: 2026-06-12 03:54:35.882676

"""
from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = '762c07784edc'
down_revision: Union[str, None] = '7aa59fe7bbf8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
