"""Sprint 5

Revision ID: 7aa59fe7bbf8
Revises: afe75119303a
Create Date: 2026-06-12 03:37:18.645627

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '7aa59fe7bbf8'
down_revision: Union[str, None] = 'afe75119303a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    bind = op.get_bind()
    schema_system = 'system' if bind.dialect.name != 'sqlite' else None
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('asset_health',
    sa.Column('asset_id', sa.Uuid(), nullable=False),
    sa.Column('provider_name', sa.String(), nullable=False),
    sa.Column('last_successful_ingestion', sa.DateTime(), nullable=True),
    sa.Column('quote_age_seconds', sa.Integer(), nullable=True),
    sa.Column('fundamentals_age_seconds', sa.Integer(), nullable=True),
    sa.Column('signal_age_seconds', sa.Integer(), nullable=True),
    sa.Column('news_age_seconds', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('asset_id', 'provider_name', name=op.f('pk_asset_health')),
    schema='market'
    )
    op.create_table('job_runs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('job_name', sa.String(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('rows_processed', sa.Integer(), nullable=False),
    sa.Column('error', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_job_runs')),
    schema='system'
    )
    with op.batch_alter_table('failed_ingestions', schema=schema_system) as batch_op:
        batch_op.add_column(sa.Column('is_exhausted', sa.Boolean(), nullable=False, server_default='0'))
    # ### end Alembic commands ###


def downgrade() -> None:
    bind = op.get_bind()
    schema_system = 'system' if bind.dialect.name != 'sqlite' else None
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('job_runs', schema='system')
    op.drop_table('asset_health', schema='market')
    with op.batch_alter_table('failed_ingestions', schema=schema_system) as batch_op:
        batch_op.drop_column('is_exhausted')
    # ### end Alembic commands ###
