"""add wallet to transactions, widen position uniqueness

Revision ID: 7e8a272774af
Revises: 630dbcacdc95
Create Date: 2026-07-27 17:27:13.484063

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7e8a272774af'
down_revision: Union[str, None] = '630dbcacdc95'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('idx_positions_portfolio_symbol'), table_name='positions', schema='portfolio')
    op.create_index('idx_positions_portfolio_symbol', 'positions', ['portfolio_id', 'symbol', 'wallet'], unique=True, schema='portfolio')
    op.add_column(
        'transactions',
        sa.Column('wallet', sa.String(), nullable=False, server_default='spot'),
        schema='portfolio',
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transactions', 'wallet', schema='portfolio')
    op.drop_index('idx_positions_portfolio_symbol', table_name='positions', schema='portfolio')
    op.create_index(op.f('idx_positions_portfolio_symbol'), 'positions', ['portfolio_id', 'symbol'], unique=True, schema='portfolio')
    # ### end Alembic commands ###
