"""add task_runs table

Revision ID: 8ba682b2d648
Revises: 682d73d52b1a
Create Date: 2026-07-16 13:58:49.020881

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8ba682b2d648'
down_revision: Union[str, None] = '682d73d52b1a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('task_runs',
    sa.Column('task_name', sa.String(), nullable=False),
    sa.Column('task_id', sa.String(), nullable=False),
    sa.Column('asset_id', sa.String(), nullable=True),
    sa.Column('status', sa.Enum('STARTED', 'SUCCESS', 'FAILED', name='taskrunstatus'), nullable=False),
    sa.Column('error_message', sa.String(), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_task_runs')),
    schema='system'
    )
    op.create_index('idx_task_runs_started_at_desc', 'task_runs', [sa.literal_column('started_at DESC')], unique=False, schema='system')
    op.create_index('idx_task_runs_task_name_asset_id', 'task_runs', ['task_name', 'asset_id'], unique=False, schema='system')
    op.create_index(op.f('ix_system_task_runs_task_id'), 'task_runs', ['task_id'], unique=False, schema='system')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_system_task_runs_task_id'), table_name='task_runs', schema='system')
    op.drop_index('idx_task_runs_task_name_asset_id', table_name='task_runs', schema='system')
    op.drop_index('idx_task_runs_started_at_desc', table_name='task_runs', schema='system')
    op.drop_table('task_runs', schema='system')
    # ### end Alembic commands ###
