"""add last_news_fetch_at to assets

Revision ID: 93ce033de8cf
Revises: ab85b80e72b4
Create Date: 2026-07-15 21:38:45.259871

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '93ce033de8cf'
down_revision: Union[str, None] = 'ab85b80e72b4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assets', sa.Column('last_news_fetch_at', sa.DateTime(), nullable=True), schema='market')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('assets', 'last_news_fetch_at', schema='market')
    # ### end Alembic commands ###
