"""add binance_backfill_progress table

Revision ID: 942dce1f19c8
Revises: f9aace3f94f2
Create Date: 2026-07-20 08:52:20.255563

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '942dce1f19c8'
down_revision: Union[str, None] = 'f9aace3f94f2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('binance_backfill_progress',
    sa.Column('portfolio_id', sa.Uuid(), nullable=False),
    sa.Column('symbol', sa.String(), nullable=False),
    sa.Column('last_from_id', sa.BigInteger(), nullable=True),
    sa.Column('trades_fetched', sa.Integer(), nullable=False),
    sa.Column('trades_imported', sa.Integer(), nullable=False),
    sa.Column('done', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['portfolio_id'], ['portfolio.portfolios.id'], name=op.f('fk_binance_backfill_progress_portfolio_id'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_binance_backfill_progress')),
    sa.UniqueConstraint('portfolio_id', 'symbol', name='uq_binance_backfill_progress_portfolio_symbol'),
    schema='portfolio'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('binance_backfill_progress', schema='portfolio')
    # ### end Alembic commands ###
