"""add watchlist alert direction and triggered state

Revision ID: 9a7ae6e25211
Revises: 8ba682b2d648
Create Date: 2026-07-16 18:22:48.923474

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9a7ae6e25211'
down_revision: Union[str, None] = '8ba682b2d648'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('watchlist_symbols', sa.Column('alert_direction', sa.String(length=3), nullable=True), schema='watchlist')
    op.add_column('watchlist_symbols', sa.Column('alert_triggered', sa.Boolean(), nullable=False, server_default=sa.text('false')), schema='watchlist')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('watchlist_symbols', 'alert_triggered', schema='watchlist')
    op.drop_column('watchlist_symbols', 'alert_direction', schema='watchlist')
    # ### end Alembic commands ###
