"""drop dead job_configs config column

Revision ID: a01d61e3e204
Revises: 5f0cf3688bca
Create Date: 2026-07-12 14:47:45.912923

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a01d61e3e204'
down_revision: Union[str, None] = '5f0cf3688bca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('job_configs', 'config', schema='config')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('job_configs', sa.Column('config', sa.TEXT(), server_default='{}', autoincrement=False, nullable=False), schema='config')
    # ### end Alembic commands ###
