"""extend provider_configs for plugin registry

Adds the provider-registry lifecycle/capability columns used by
app.core.providers (status, capabilities, priority, health, rate_limit,
timeout_seconds, retry_policy, cache_ttl_seconds) to config.provider_configs.
Hand-written (not autogenerated) because this dev database has unrelated
schema drift from migration history that autogenerate would have picked up.

Revision ID: a3f1c9d02b4e
Revises: 87fb0a5ffea7
Create Date: 2026-07-03
"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy import inspect

revision: str = "a3f1c9d02b4e"
down_revision: Union[str, None] = "87fb0a5ffea7"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

_TABLE = "provider_configs"
_SCHEMA = "config"

_NEW_COLUMNS = [
    # server_default is a plain value here (not pre-quoted) — SQLAlchemy's
    # DefaultClause quotes string literals itself; passing an already-quoted
    # string double-quotes it in the generated DDL.
    ("status", sa.String(16), False, "PLANNED"),
    ("capabilities", sa.Text(), False, "[]"),
    ("priority", sa.Integer(), False, "100"),
    ("health", sa.Text(), False, "{}"),
    ("rate_limit", sa.String(64), True, None),
    ("timeout_seconds", sa.Integer(), False, "10"),
    ("retry_policy", sa.Text(), False, "{}"),
    ("cache_ttl_seconds", sa.Integer(), True, None),
]


def _has_column(table: str, column: str, schema: str) -> bool:
    bind = op.get_bind()
    inspector = inspect(bind)
    return column in [c["name"] for c in inspector.get_columns(table, schema=schema)]


def upgrade() -> None:
    for name, col_type, nullable, server_default in _NEW_COLUMNS:
        if not _has_column(_TABLE, name, schema=_SCHEMA):
            op.add_column(
                _TABLE,
                sa.Column(name, col_type, nullable=nullable, server_default=server_default),
                schema=_SCHEMA,
            )
            if server_default is not None:
                # Drop the server_default after backfilling existing rows so the ORM
                # (which sets defaults in Python) stays the single source of truth.
                op.alter_column(_TABLE, name, server_default=None, schema=_SCHEMA)


def downgrade() -> None:
    for name, _col_type, _nullable, _server_default in _NEW_COLUMNS:
        if _has_column(_TABLE, name, schema=_SCHEMA):
            op.drop_column(_TABLE, name, schema=_SCHEMA)
