"""add asset_fundamentals table

Revision ID: ab85b80e72b4
Revises: ad9c01814823
Create Date: 2026-07-13 17:03:52.246217

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ab85b80e72b4'
down_revision: Union[str, None] = 'ad9c01814823'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('asset_fundamentals',
    sa.Column('asset_id', sa.Uuid(), nullable=False),
    sa.Column('trailing_pe', sa.Numeric(), nullable=True),
    sa.Column('price_to_book', sa.Numeric(), nullable=True),
    sa.Column('roe', sa.Numeric(), nullable=True),
    sa.Column('debt_to_equity', sa.Numeric(), nullable=True),
    sa.Column('profit_margin', sa.Numeric(), nullable=True),
    sa.Column('revenue_growth', sa.Numeric(), nullable=True),
    sa.Column('dividend_yield', sa.Numeric(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['market.asset_snapshot.asset_id'], name=op.f('fk_asset_fundamentals_asset_id'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('asset_id', name=op.f('pk_asset_fundamentals')),
    schema='market'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('asset_fundamentals', schema='market')
    # ### end Alembic commands ###
