"""Sprint 4

Revision ID: afe75119303a
Revises: 000c4dd571f2
Create Date: 2026-06-12 03:10:24.463707

"""
from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'afe75119303a'
down_revision: Union[str, None] = '000c4dd571f2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('asset_scores',
    sa.Column('asset_id', sa.Uuid(), nullable=False),
    sa.Column('model_version', sa.String(), nullable=False),
    sa.Column('recommendation_score', sa.Numeric(), nullable=False),
    sa.Column('quality_score', sa.Numeric(), nullable=False),
    sa.Column('valuation_score', sa.Numeric(), nullable=False),
    sa.Column('generated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('asset_id', 'model_version', name=op.f('pk_asset_scores')),
    schema='evaluation'
    )
    op.create_table('feature_snapshots',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('asset_id', sa.Uuid(), nullable=False),
    sa.Column('snapshot_at', sa.DateTime(), nullable=False),
    sa.Column('model_version', sa.String(), nullable=False),
    sa.Column('feature_schema_version', sa.String(), nullable=False),
    sa.Column('features', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_feature_snapshots')),
    schema='evaluation'
    )
    op.create_table('asset_features',
    sa.Column('asset_id', sa.Uuid(), nullable=False),
    sa.Column('price', sa.Numeric(), nullable=True),
    sa.Column('market_cap', sa.Numeric(), nullable=True),
    sa.Column('momentum_score', sa.Numeric(), nullable=True),
    sa.Column('volatility_score', sa.Numeric(), nullable=True),
    sa.Column('sentiment_score', sa.Numeric(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('asset_id', name=op.f('pk_asset_features')),
    schema='market'
    )
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    op.drop_table('asset_features', schema='market')
    op.drop_table('feature_snapshots', schema='evaluation')
    op.drop_table('asset_scores', schema='evaluation')
    # ### end Alembic commands ###
