"""baseline schema

Revision ID: f5dc9f64c088
Revises: 
Create Date: 2026-07-06 20:27:10.687402

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f5dc9f64c088'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    bind = op.get_bind()
    if bind.dialect.name != 'sqlite':
        for schema in ('system', 'market', 'portfolio', 'evaluation', 'recommendation', 'watchlist', 'config', 'notification', 'news', 'ai'):
            op.execute(f"CREATE SCHEMA IF NOT EXISTS {schema}")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_briefings',
    sa.Column('briefing_type', sa.String(length=30), nullable=False),
    sa.Column('symbol', sa.String(length=30), nullable=True),
    sa.Column('content', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('model_used', sa.String(length=100), nullable=False),
    sa.Column('prompt_tokens', sa.Integer(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ai_briefings')),
    schema='ai'
    )
    op.create_index('idx_ai_briefings_type', 'ai_briefings', ['briefing_type'], unique=False, schema='ai')
    op.create_table('allocation_targets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('asset_class', sa.String(length=40), nullable=False),
    sa.Column('target_pct', sa.Integer(), nullable=False),
    sa.Column('band_low_pct', sa.Integer(), nullable=True),
    sa.Column('band_high_pct', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_allocation_targets')),
    schema='config'
    )
    op.create_index(op.f('ix_config_allocation_targets_asset_class'), 'allocation_targets', ['asset_class'], unique=True, schema='config')
    op.create_index(op.f('ix_config_allocation_targets_id'), 'allocation_targets', ['id'], unique=False, schema='config')
    op.create_table('job_configs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_name', sa.String(length=64), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('cron_expression', sa.String(length=64), nullable=False),
    sa.Column('last_run_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('next_run_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('job_tier', sa.String(length=16), nullable=False),
    sa.Column('config', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_job_configs')),
    schema='config'
    )
    op.create_index(op.f('ix_config_job_configs_id'), 'job_configs', ['id'], unique=False, schema='config')
    op.create_index(op.f('ix_config_job_configs_job_name'), 'job_configs', ['job_name'], unique=True, schema='config')
    op.create_table('job_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_name', sa.String(length=64), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'RUNNING', 'SUCCESS', 'FAILED', name='jobstatus'), nullable=False),
    sa.Column('task_id', sa.String(length=512), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_job_logs')),
    schema='config'
    )
    op.create_index(op.f('ix_config_job_logs_id'), 'job_logs', ['id'], unique=False, schema='config')
    op.create_index(op.f('ix_config_job_logs_job_name'), 'job_logs', ['job_name'], unique=False, schema='config')
    op.create_table('provider_configs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('provider_name', sa.String(length=64), nullable=False),
    sa.Column('provider_type', sa.String(length=32), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('key_names', sa.Text(), nullable=False),
    sa.Column('encrypted_keys', sa.Text(), nullable=False),
    sa.Column('config', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('capabilities', sa.Text(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('health', sa.Text(), nullable=False),
    sa.Column('rate_limit', sa.String(length=64), nullable=True),
    sa.Column('timeout_seconds', sa.Integer(), nullable=False),
    sa.Column('retry_policy', sa.Text(), nullable=False),
    sa.Column('cache_ttl_seconds', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_provider_configs')),
    schema='config'
    )
    op.create_index(op.f('ix_config_provider_configs_id'), 'provider_configs', ['id'], unique=False, schema='config')
    op.create_index(op.f('ix_config_provider_configs_provider_name'), 'provider_configs', ['provider_name'], unique=True, schema='config')
    # Not represented in the ProviderConfig model (status is a plain String column) —
    # kept in sync with app.core.providers.lifecycle.ProviderStatus. See former migration
    # b7c2e4f19a3d; adding a new lifecycle value requires widening this constraint.
    op.create_check_constraint(
        'status_valid',
        'provider_configs',
        sa.text("status IN ('PLANNED', 'STUB', 'PARTIAL', 'ACTIVE', 'DISABLED', 'DEPRECATED', 'FAILED')"),
        schema='config',
    )
    op.create_table('asset_snapshot',
    sa.Column('asset_id', sa.Uuid(), nullable=False),
    sa.Column('price', sa.Numeric(), nullable=True),
    sa.Column('market_cap', sa.Numeric(), nullable=True),
    sa.Column('pe_ratio', sa.Numeric(), nullable=True),
    sa.Column('rsi', sa.Numeric(), nullable=True),
    sa.Column('momentum_score', sa.Numeric(), nullable=True),
    sa.Column('volatility_score', sa.Numeric(), nullable=True),
    sa.Column('sentiment_score', sa.Numeric(), nullable=True),
    sa.Column('payload', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('asset_id', name=op.f('pk_asset_snapshot')),
    schema='market'
    )
    op.create_table('assets',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('symbol', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('asset_class', sa.String(), nullable=False),
    sa.Column('metadata', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('classification', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_assets')),
    schema='market'
    )
    op.create_index('idx_assets_symbol', 'assets', ['symbol'], unique=True, schema='market')
    op.create_table('latest_quotes',
    sa.Column('symbol', sa.String(), nullable=False),
    sa.Column('asset_id', sa.Uuid(), nullable=True),
    sa.Column('price', sa.Numeric(), nullable=False),
    sa.Column('volume', sa.Numeric(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('symbol', name=op.f('pk_latest_quotes')),
    schema='market'
    )
    op.create_index(op.f('ix_market_latest_quotes_asset_id'), 'latest_quotes', ['asset_id'], unique=True, schema='market')
    op.create_table('theme_weights',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('theme_id', sa.String(length=40), nullable=False),
    sa.Column('symbol', sa.String(length=40), nullable=False),
    sa.Column('weight', sa.Numeric(), nullable=False),
    sa.Column('effective_date', sa.String(length=20), nullable=False),
    sa.Column('mcap_at_set', sa.Numeric(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_theme_weights')),
    schema='market'
    )
    op.create_index('idx_theme_weight_theme_date', 'theme_weights', ['theme_id', 'effective_date'], unique=False, schema='market')
    op.create_index(op.f('ix_market_theme_weights_theme_id'), 'theme_weights', ['theme_id'], unique=False, schema='market')
    op.create_table('news',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('url', sa.String(), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sentiment_score', sa.Float(), nullable=True),
    sa.Column('relevance_score', sa.Float(), nullable=True),
    sa.Column('symbols', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_news')),
    sa.UniqueConstraint('url', name=op.f('uq_news_url')),
    schema='news'
    )
    op.create_index(op.f('ix_news_news_id'), 'news', ['id'], unique=False, schema='news')
    op.create_table('portfolios',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_portfolios')),
    schema='portfolio'
    )
    op.create_table('failed_ingestions',
    sa.Column('provider', sa.String(), nullable=False),
    sa.Column('payload', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('error', sa.String(), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('is_exhausted', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_failed_ingestions')),
    schema='system'
    )
    op.create_index('idx_failed_ingestions_created_at_desc', 'failed_ingestions', [sa.literal_column('created_at DESC')], unique=False, schema='system')
    op.create_index('idx_failed_ingestions_is_exhausted', 'failed_ingestions', ['is_exhausted'], unique=False, schema='system')
    op.create_table('job_runs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('job_name', sa.String(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('rows_processed', sa.Integer(), nullable=False),
    sa.Column('error', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_job_runs')),
    schema='system'
    )
    op.create_index('idx_job_runs_started_at_desc', 'job_runs', [sa.literal_column('started_at DESC')], unique=False, schema='system')
    op.create_index('idx_job_runs_status', 'job_runs', ['status'], unique=False, schema='system')
    op.create_table('providers',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=True),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.Column('health_status', sa.String(), nullable=True),
    sa.Column('last_success_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_providers')),
    sa.UniqueConstraint('name', name=op.f('uq_providers_name')),
    schema='system'
    )
    op.create_table('users',
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('first_name', sa.String(), nullable=True),
    sa.Column('last_name', sa.String(), nullable=True),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('profile_picture', sa.String(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    schema='system'
    )
    op.create_index(op.f('ix_system_users_email'), 'users', ['email'], unique=True, schema='system')
    op.create_index(op.f('ix_system_users_phone'), 'users', ['phone'], unique=False, schema='system')
    op.create_table('ai_generations',
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('feature_name', sa.String(length=64), nullable=False),
    sa.Column('provider', sa.String(length=64), nullable=False),
    sa.Column('model', sa.String(length=128), nullable=False),
    sa.Column('prompt_version', sa.String(length=32), nullable=True),
    sa.Column('prompt_text', sa.Text(), nullable=False),
    sa.Column('context_payload', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('retrieval_metadata', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('response_text', sa.Text(), nullable=False),
    sa.Column('prompt_tokens', sa.Integer(), nullable=True),
    sa.Column('completion_tokens', sa.Integer(), nullable=True),
    sa.Column('total_tokens', sa.Integer(), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('execution_trace', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('generation_parameters', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('prompt_sha256', sa.String(length=64), nullable=True),
    sa.Column('data_classification', sa.String(length=32), nullable=True),
    sa.Column('payload_retention_state', sa.String(length=32), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['system.users.id'], name=op.f('fk_ai_generations_user_id'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ai_generations')),
    schema='ai'
    )
    op.create_index('idx_ai_generations_user_feature', 'ai_generations', ['user_id', 'feature_name'], unique=False, schema='ai')
    op.create_table('asset_scores',
    sa.Column('asset_id', sa.Uuid(), nullable=False),
    sa.Column('model_version', sa.String(), nullable=False),
    sa.Column('recommendation_score', sa.Numeric(), nullable=False),
    sa.Column('quality_score', sa.Numeric(), nullable=False),
    sa.Column('valuation_score', sa.Numeric(), nullable=False),
    sa.Column('generated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['market.asset_snapshot.asset_id'], name=op.f('fk_asset_scores_asset_id'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('asset_id', 'model_version', name=op.f('pk_asset_scores')),
    schema='evaluation'
    )
    op.create_index('idx_asset_scores_asset_generated_at', 'asset_scores', ['asset_id', sa.literal_column('generated_at DESC')], unique=False, schema='evaluation')
    op.create_table('feature_snapshots',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('asset_id', sa.Uuid(), nullable=False),
    sa.Column('snapshot_at', sa.DateTime(), nullable=False),
    sa.Column('model_version', sa.String(), nullable=False),
    sa.Column('feature_schema_version', sa.String(), nullable=False),
    sa.Column('features', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['market.asset_snapshot.asset_id'], name=op.f('fk_feature_snapshots_asset_id'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_feature_snapshots')),
    schema='evaluation'
    )
    op.create_index('idx_feature_snapshots_asset_snapshot_at', 'feature_snapshots', ['asset_id', sa.literal_column('snapshot_at DESC')], unique=False, schema='evaluation')
    op.create_table('asset_features',
    sa.Column('asset_id', sa.Uuid(), nullable=False),
    sa.Column('price', sa.Numeric(), nullable=True),
    sa.Column('market_cap', sa.Numeric(), nullable=True),
    sa.Column('momentum_score', sa.Numeric(), nullable=True),
    sa.Column('volatility_score', sa.Numeric(), nullable=True),
    sa.Column('sentiment_score', sa.Numeric(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['market.asset_snapshot.asset_id'], name=op.f('fk_asset_features_asset_id'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('asset_id', name=op.f('pk_asset_features')),
    schema='market'
    )
    op.create_table('asset_health',
    sa.Column('asset_id', sa.Uuid(), nullable=False),
    sa.Column('provider_name', sa.String(), nullable=False),
    sa.Column('last_successful_ingestion', sa.DateTime(), nullable=True),
    sa.Column('quote_age_seconds', sa.Integer(), nullable=True),
    sa.Column('fundamentals_age_seconds', sa.Integer(), nullable=True),
    sa.Column('signal_age_seconds', sa.Integer(), nullable=True),
    sa.Column('news_age_seconds', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['market.asset_snapshot.asset_id'], name=op.f('fk_asset_health_asset_id'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('asset_id', 'provider_name', name=op.f('pk_asset_health')),
    schema='market'
    )
    op.create_index('idx_asset_health_status', 'asset_health', ['status'], unique=False, schema='market')
    op.create_index('idx_asset_health_updated_at', 'asset_health', [sa.literal_column('updated_at DESC')], unique=False, schema='market')
    op.create_table('market_themes',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('theme_id', sa.String(length=40), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('desc', sa.String(), nullable=False),
    sa.Column('symbols', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('ret1m', sa.Numeric(), nullable=False),
    sa.Column('owner_id', sa.Uuid(), nullable=True),
    sa.Column('forked_from', sa.String(length=40), nullable=True),
    sa.Column('inception_date', sa.String(length=20), nullable=True),
    sa.Column('is_public', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['system.users.id'], name=op.f('fk_market_themes_owner_id'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_market_themes')),
    schema='market'
    )
    op.create_index(op.f('ix_market_market_themes_owner_id'), 'market_themes', ['owner_id'], unique=False, schema='market')
    op.create_index(op.f('ix_market_market_themes_theme_id'), 'market_themes', ['theme_id'], unique=True, schema='market')
    op.create_table('price_history',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('asset_id', sa.Uuid(), nullable=False),
    sa.Column('symbol', sa.String(), nullable=False),
    sa.Column('price', sa.Numeric(), nullable=False),
    sa.Column('volume', sa.Numeric(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['market.assets.id'], name=op.f('fk_price_history_asset_id'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_price_history')),
    schema='market'
    )
    op.create_index('idx_price_history_asset_time', 'price_history', ['asset_id', 'timestamp'], unique=False, schema='market')
    op.create_table('asset_sentiment_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('asset_id', sa.Uuid(), nullable=False),
    sa.Column('snapshot_date', sa.DateTime(), nullable=False),
    sa.Column('avg_sentiment_7d', sa.Float(), nullable=True),
    sa.Column('avg_sentiment_30d', sa.Float(), nullable=True),
    sa.Column('article_count_7d', sa.Integer(), nullable=True),
    sa.Column('trend', sa.String(length=20), nullable=True),
    sa.Column('computed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['market.assets.id'], name=op.f('fk_asset_sentiment_snapshots_asset_id')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_asset_sentiment_snapshots')),
    sa.UniqueConstraint('asset_id', 'snapshot_date', name='uq_sentiment_asset_date'),
    schema='news'
    )
    op.create_table('news_assets',
    sa.Column('news_id', sa.Integer(), nullable=False),
    sa.Column('asset_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['market.assets.id'], name=op.f('fk_news_assets_asset_id'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['news_id'], ['news.news.id'], name=op.f('fk_news_assets_news_id'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('news_id', 'asset_id', name=op.f('pk_news_assets')),
    schema='news'
    )
    op.create_index('idx_news_assets_asset', 'news_assets', ['asset_id'], unique=False, schema='news')
    op.create_table('web_notifications',
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('read', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['system.users.id'], name=op.f('fk_web_notifications_user_id'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_web_notifications')),
    schema='notification'
    )
    op.create_index(op.f('ix_notification_web_notifications_user_id'), 'web_notifications', ['user_id'], unique=False, schema='notification')
    op.create_table('positions',
    sa.Column('portfolio_id', sa.Uuid(), nullable=False),
    sa.Column('symbol', sa.String(), nullable=False),
    sa.Column('asset_id', sa.Uuid(), nullable=True),
    sa.Column('quantity', sa.Numeric(), nullable=False),
    sa.Column('avg_buy_price', sa.Numeric(), nullable=False),
    sa.Column('wallet', sa.String(), nullable=False),
    sa.Column('leverage', sa.Numeric(), nullable=True),
    sa.Column('liquidation_price', sa.Numeric(), nullable=True),
    sa.Column('unrealized_pnl', sa.Numeric(), nullable=True),
    sa.Column('side', sa.String(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['market.asset_snapshot.asset_id'], name=op.f('fk_positions_asset_id'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['portfolio_id'], ['portfolio.portfolios.id'], name=op.f('fk_positions_portfolio_id'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_positions')),
    schema='portfolio'
    )
    op.create_index('idx_positions_portfolio_symbol', 'positions', ['portfolio_id', 'symbol'], unique=True, schema='portfolio')
    op.create_table('snapshots',
    sa.Column('portfolio_id', sa.Uuid(), nullable=False),
    sa.Column('market_value', sa.Numeric(), nullable=True),
    sa.Column('cash_balance', sa.Numeric(), nullable=True),
    sa.Column('allocation', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('daily_return', sa.Numeric(), nullable=True),
    sa.Column('total_return', sa.Numeric(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['portfolio_id'], ['portfolio.portfolios.id'], name=op.f('fk_snapshots_portfolio_id'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('portfolio_id', name=op.f('pk_snapshots')),
    schema='portfolio'
    )
    op.create_table('transactions',
    sa.Column('portfolio_id', sa.Uuid(), nullable=False),
    sa.Column('symbol', sa.String(), nullable=False),
    sa.Column('asset_id', sa.Uuid(), nullable=True),
    sa.Column('transaction_type', sa.String(), nullable=False),
    sa.Column('quantity', sa.Numeric(), nullable=False),
    sa.Column('price', sa.Numeric(), nullable=False),
    sa.Column('transaction_date', sa.DateTime(), nullable=False),
    sa.Column('fees', sa.Numeric(), nullable=False),
    sa.Column('taxes', sa.Numeric(), nullable=False),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('broker', sa.String(), nullable=True),
    sa.Column('broker_reference', sa.String(), nullable=True),
    sa.Column('kind', sa.String(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['market.asset_snapshot.asset_id'], name=op.f('fk_transactions_asset_id'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['portfolio_id'], ['portfolio.portfolios.id'], name=op.f('fk_transactions_portfolio_id'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_transactions')),
    schema='portfolio'
    )
    op.create_index(op.f('ix_portfolio_transactions_symbol'), 'transactions', ['symbol'], unique=False, schema='portfolio')
    op.create_index(op.f('ix_portfolio_transactions_transaction_date'), 'transactions', ['transaction_date'], unique=False, schema='portfolio')
    # Not represented in the Transaction model — dedupes broker-synced transactions.
    # See former migration c1a9f4d7e2b6.
    op.create_index(
        'ix_transactions_broker_dedup',
        'transactions',
        ['portfolio_id', 'broker', 'broker_reference'],
        unique=True,
        schema='portfolio',
        postgresql_where=sa.text('broker_reference IS NOT NULL'),
    )
    op.create_table('recommendations',
    sa.Column('asset_id', sa.Uuid(), nullable=False),
    sa.Column('recommendation_state', sa.String(length=20), nullable=False),
    sa.Column('confidence_score', sa.Numeric(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('version', sa.String(length=20), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['market.asset_snapshot.asset_id'], name=op.f('fk_recommendations_asset_id'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_recommendations')),
    schema='recommendation'
    )
    op.create_index('idx_recommendations_asset', 'recommendations', ['asset_id'], unique=False, schema='recommendation')
    op.create_index('idx_recommendations_status', 'recommendations', ['status'], unique=False, schema='recommendation')
    op.create_table('audit_logs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('actor_id', sa.Uuid(), nullable=True),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('entity_type', sa.String(), nullable=False),
    sa.Column('entity_id', sa.String(), nullable=True),
    sa.Column('details', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['system.users.id'], name=op.f('fk_audit_logs_actor_id'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_logs')),
    schema='system'
    )
    op.create_index('idx_audit_logs_action_time', 'audit_logs', ['action', sa.literal_column('created_at DESC')], unique=False, schema='system')
    op.create_table('provider_usage',
    sa.Column('provider_id', sa.Uuid(), nullable=False),
    sa.Column('endpoint', sa.String(), nullable=False),
    sa.Column('request_count', sa.Integer(), nullable=False),
    sa.Column('cost_estimate', sa.Numeric(), nullable=False),
    sa.Column('recorded_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['provider_id'], ['system.providers.id'], name=op.f('fk_provider_usage_provider_id'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_provider_usage')),
    schema='system'
    )
    op.create_index('idx_provider_usage_provider_recorded_at', 'provider_usage', ['provider_id', sa.literal_column('recorded_at DESC')], unique=False, schema='system')
    op.create_table('user_preferences',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('risk_profile', sa.String(), nullable=True),
    sa.Column('target_profit_pct', sa.Numeric(), nullable=True),
    sa.Column('monthly_saving', sa.Numeric(), nullable=True),
    sa.Column('working_area', sa.String(), nullable=True),
    sa.Column('swing_trading_enabled', sa.Boolean(), nullable=False),
    sa.Column('bio', sa.String(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['system.users.id'], name=op.f('fk_user_preferences_user_id'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_preferences')),
    schema='system'
    )
    op.create_index(op.f('ix_system_user_preferences_user_id'), 'user_preferences', ['user_id'], unique=True, schema='system')
    op.create_table('watchlists',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['system.users.id'], name=op.f('fk_watchlists_user_id'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_watchlists')),
    sa.UniqueConstraint('user_id', 'name', name='uq_watchlist_user_name'),
    schema='watchlist'
    )
    op.create_index(op.f('ix_watchlist_watchlists_user_id'), 'watchlists', ['user_id'], unique=False, schema='watchlist')
    op.create_table('ai_evaluations',
    sa.Column('generation_id', sa.Uuid(), nullable=False),
    sa.Column('faithfulness_score', sa.Numeric(), nullable=True),
    sa.Column('relevance_score', sa.Numeric(), nullable=True),
    sa.Column('data_reference_validated', sa.Boolean(), nullable=False),
    sa.Column('validation_details', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['generation_id'], ['ai.ai_generations.id'], name=op.f('fk_ai_evaluations_generation_id'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ai_evaluations')),
    schema='ai'
    )
    op.create_table('ai_feedback',
    sa.Column('generation_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['generation_id'], ['ai.ai_generations.id'], name=op.f('fk_ai_feedback_generation_id'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['system.users.id'], name=op.f('fk_ai_feedback_user_id'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ai_feedback')),
    schema='ai'
    )
    op.create_table('recommendation_explanations',
    sa.Column('recommendation_id', sa.Uuid(), nullable=False),
    sa.Column('rules_matched', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('reasoning', sa.String(), nullable=False),
    sa.Column('confidence_factors', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.ForeignKeyConstraint(['recommendation_id'], ['recommendation.recommendations.id'], name=op.f('fk_recommendation_explanations_recommendation_id'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('recommendation_id', name=op.f('pk_recommendation_explanations')),
    schema='recommendation'
    )
    op.create_table('recommendation_outcomes',
    sa.Column('recommendation_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('action_taken_at', sa.DateTime(), nullable=False),
    sa.Column('dismiss_reason', sa.String(), nullable=True),
    sa.Column('ledger_transaction_id', sa.Uuid(), nullable=True),
    sa.Column('predicted_impact', sa.Numeric(), nullable=True),
    sa.Column('realized_impact', sa.Numeric(), nullable=True),
    sa.ForeignKeyConstraint(['ledger_transaction_id'], ['portfolio.transactions.id'], name=op.f('fk_recommendation_outcomes_ledger_transaction_id'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['recommendation_id'], ['recommendation.recommendations.id'], name=op.f('fk_recommendation_outcomes_recommendation_id'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('recommendation_id', name=op.f('pk_recommendation_outcomes')),
    schema='recommendation'
    )
    op.create_table('watchlist_symbols',
    sa.Column('watchlist_id', sa.Uuid(), nullable=False),
    sa.Column('symbol', sa.String(length=60), nullable=False),
    sa.Column('alert_price', sa.Numeric(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['watchlist_id'], ['watchlist.watchlists.id'], name=op.f('fk_watchlist_symbols_watchlist_id'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_watchlist_symbols')),
    sa.UniqueConstraint('watchlist_id', 'symbol', name='uq_watchlist_symbol'),
    schema='watchlist'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('watchlist_symbols', schema='watchlist')
    op.drop_table('recommendation_outcomes', schema='recommendation')
    op.drop_table('recommendation_explanations', schema='recommendation')
    op.drop_table('ai_feedback', schema='ai')
    op.drop_table('ai_evaluations', schema='ai')
    op.drop_index(op.f('ix_watchlist_watchlists_user_id'), table_name='watchlists', schema='watchlist')
    op.drop_table('watchlists', schema='watchlist')
    op.drop_index(op.f('ix_system_user_preferences_user_id'), table_name='user_preferences', schema='system')
    op.drop_table('user_preferences', schema='system')
    op.drop_index('idx_provider_usage_provider_recorded_at', table_name='provider_usage', schema='system')
    op.drop_table('provider_usage', schema='system')
    op.drop_index('idx_audit_logs_action_time', table_name='audit_logs', schema='system')
    op.drop_table('audit_logs', schema='system')
    op.drop_index('idx_recommendations_status', table_name='recommendations', schema='recommendation')
    op.drop_index('idx_recommendations_asset', table_name='recommendations', schema='recommendation')
    op.drop_table('recommendations', schema='recommendation')
    op.drop_index('ix_transactions_broker_dedup', table_name='transactions', schema='portfolio')
    op.drop_index(op.f('ix_portfolio_transactions_transaction_date'), table_name='transactions', schema='portfolio')
    op.drop_index(op.f('ix_portfolio_transactions_symbol'), table_name='transactions', schema='portfolio')
    op.drop_table('transactions', schema='portfolio')
    op.drop_table('snapshots', schema='portfolio')
    op.drop_index('idx_positions_portfolio_symbol', table_name='positions', schema='portfolio')
    op.drop_table('positions', schema='portfolio')
    op.drop_index(op.f('ix_notification_web_notifications_user_id'), table_name='web_notifications', schema='notification')
    op.drop_table('web_notifications', schema='notification')
    op.drop_index('idx_news_assets_asset', table_name='news_assets', schema='news')
    op.drop_table('news_assets', schema='news')
    op.drop_table('asset_sentiment_snapshots', schema='news')
    op.drop_index('idx_price_history_asset_time', table_name='price_history', schema='market')
    op.drop_table('price_history', schema='market')
    op.drop_index(op.f('ix_market_market_themes_theme_id'), table_name='market_themes', schema='market')
    op.drop_index(op.f('ix_market_market_themes_owner_id'), table_name='market_themes', schema='market')
    op.drop_table('market_themes', schema='market')
    op.drop_index('idx_asset_health_updated_at', table_name='asset_health', schema='market')
    op.drop_index('idx_asset_health_status', table_name='asset_health', schema='market')
    op.drop_table('asset_health', schema='market')
    op.drop_table('asset_features', schema='market')
    op.drop_index('idx_feature_snapshots_asset_snapshot_at', table_name='feature_snapshots', schema='evaluation')
    op.drop_table('feature_snapshots', schema='evaluation')
    op.drop_index('idx_asset_scores_asset_generated_at', table_name='asset_scores', schema='evaluation')
    op.drop_table('asset_scores', schema='evaluation')
    op.drop_index('idx_ai_generations_user_feature', table_name='ai_generations', schema='ai')
    op.drop_table('ai_generations', schema='ai')
    op.drop_index(op.f('ix_system_users_phone'), table_name='users', schema='system')
    op.drop_index(op.f('ix_system_users_email'), table_name='users', schema='system')
    op.drop_table('users', schema='system')
    op.drop_table('providers', schema='system')
    op.drop_index('idx_job_runs_status', table_name='job_runs', schema='system')
    op.drop_index('idx_job_runs_started_at_desc', table_name='job_runs', schema='system')
    op.drop_table('job_runs', schema='system')
    op.drop_index('idx_failed_ingestions_is_exhausted', table_name='failed_ingestions', schema='system')
    op.drop_index('idx_failed_ingestions_created_at_desc', table_name='failed_ingestions', schema='system')
    op.drop_table('failed_ingestions', schema='system')
    op.drop_table('portfolios', schema='portfolio')
    op.drop_index(op.f('ix_news_news_id'), table_name='news', schema='news')
    op.drop_table('news', schema='news')
    op.drop_index(op.f('ix_market_theme_weights_theme_id'), table_name='theme_weights', schema='market')
    op.drop_index('idx_theme_weight_theme_date', table_name='theme_weights', schema='market')
    op.drop_table('theme_weights', schema='market')
    op.drop_index(op.f('ix_market_latest_quotes_asset_id'), table_name='latest_quotes', schema='market')
    op.drop_table('latest_quotes', schema='market')
    op.drop_index('idx_assets_symbol', table_name='assets', schema='market')
    op.drop_table('assets', schema='market')
    op.drop_table('asset_snapshot', schema='market')
    op.drop_constraint('ck_provider_configs_status_valid', 'provider_configs', schema='config', type_='check')
    op.drop_index(op.f('ix_config_provider_configs_provider_name'), table_name='provider_configs', schema='config')
    op.drop_index(op.f('ix_config_provider_configs_id'), table_name='provider_configs', schema='config')
    op.drop_table('provider_configs', schema='config')
    op.drop_index(op.f('ix_config_job_logs_job_name'), table_name='job_logs', schema='config')
    op.drop_index(op.f('ix_config_job_logs_id'), table_name='job_logs', schema='config')
    op.drop_table('job_logs', schema='config')
    op.drop_index(op.f('ix_config_job_configs_job_name'), table_name='job_configs', schema='config')
    op.drop_index(op.f('ix_config_job_configs_id'), table_name='job_configs', schema='config')
    op.drop_table('job_configs', schema='config')
    op.drop_index(op.f('ix_config_allocation_targets_id'), table_name='allocation_targets', schema='config')
    op.drop_index(op.f('ix_config_allocation_targets_asset_class'), table_name='allocation_targets', schema='config')
    op.drop_table('allocation_targets', schema='config')
    op.drop_index('idx_ai_briefings_type', table_name='ai_briefings', schema='ai')
    op.drop_table('ai_briefings', schema='ai')
    # ### end Alembic commands ###
