"""add recommendation_id to transactions

Revision ID: f9aace3f94f2
Revises: 2074319bf4b9
Create Date: 2026-07-18 00:13:53.821968

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f9aace3f94f2'
down_revision: Union[str, None] = '2074319bf4b9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('recommendation_id', sa.Uuid(), nullable=True), schema='portfolio')
    op.create_foreign_key(op.f('fk_transactions_recommendation_id'), 'transactions', 'recommendations', ['recommendation_id'], ['id'], source_schema='portfolio', referent_schema='recommendation', ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_transactions_recommendation_id'), 'transactions', schema='portfolio', type_='foreignkey')
    op.drop_column('transactions', 'recommendation_id', schema='portfolio')
    # ### end Alembic commands ###
