export const ROUTES = {
    DASHBOARD:       '/dashboard',
    PORTFOLIO:       '/portfolio',
    ASSETS:          '/assets',
    ASSET_DETAIL:    '/assets/:ticker',
    DECISIONS:       '/decisions',
    SIGNALS:         '/signals',
    RECOMMENDATIONS: '/recommendations',
    ACTIVITY:        '/activity',
    TRANSACTIONS:    '/transactions',
    SETTINGS:        '/settings',
    NOTIFICATIONS:   '/notifications',
    MARKETS:         '/markets',
    TERMINAL:        '/terminal',
    TERMINAL_SYM:    '/terminal/:sym',
    WATCHLIST:       '/watchlist',
    AI_BRIEFINGS:    '/briefings',
    THEME_DETAIL:    '/markets/themes/:themeId',
};
