// backend/postman/generateCollection.ts
import type { Endpoint } from "./endpoints";

function buildTestScript(e: Endpoint): string[] {
  const statusList = e.expectStatus.join(", ");
  return [
    `const expectedStatuses = [${statusList}];`,
    `pm.test("status is one of [${statusList}]", function () {`,
    `  if (expectedStatuses.length === 1) {`,
    `    pm.response.to.have.status(expectedStatuses[0]);`,
    `  } else {`,
    `    pm.expect(expectedStatuses).to.include(pm.response.code);`,
    `  }`,
    `});`,
    `pm.test("responds within 5s", function () {`,
    `  pm.expect(pm.response.responseTime).to.be.below(5000);`,
    `});`,
  ];
}

function buildRequestItem(e: Endpoint) {
  const url = `{{baseUrl}}${e.path}`;
  const item: any = {
    name: e.name,
    request: {
      method: e.method,
      header: e.body !== undefined ? [{ key: "Content-Type", value: "application/json" }] : [],
      url: {
        raw: e.query
          ? `${url}?${Object.entries(e.query).map(([key, value]) => `${key}=${value}`).join("&")}`
          : url,
        host: ["{{baseUrl}}"],
        path: e.path.replace(/^\//, "").split("/"),
        ...(e.query
          ? { query: Object.entries(e.query).map(([key, value]) => ({ key, value })) }
          : {}),
      },
      description: e.manual
        ? "MANUAL ONLY — requires live third-party redirect/session, excluded from Newman/curl automation."
        : undefined,
    },
    event: [
      {
        listen: "test",
        script: { type: "text/javascript", exec: buildTestScript(e) },
      },
    ],
  };
  if (e.body !== undefined) {
    item.request.body = { mode: "raw", raw: JSON.stringify(e.body, null, 2), options: { raw: { language: "json" } } };
  }
  return item;
}

export function buildCollection(endpoints: Endpoint[]) {
  const folders = new Map<string, Endpoint[]>();
  for (const e of endpoints) {
    if (!folders.has(e.folder)) folders.set(e.folder, []);
    folders.get(e.folder)!.push(e);
  }
  return {
    info: {
      name: "Aureon API",
      description: "Generated by backend/postman/generateCollection.ts — do not hand-edit, edit endpoints.ts instead.",
      schema: "https://schema.getpostman.com/json/collection/v2.1.0/collection.json",
    },
    item: Array.from(folders.entries()).map(([folder, items]) => ({
      name: folder,
      item: items.map(buildRequestItem),
    })),
  };
}

if (require.main === module) {
  const { ENDPOINTS } = require("./endpoints") as typeof import("./endpoints");
  const fs = require("node:fs") as typeof import("node:fs");
  const path = require("node:path") as typeof import("node:path");
  const out = buildCollection(ENDPOINTS);
  fs.writeFileSync(path.join(__dirname, "aureon.postman_collection.json"), JSON.stringify(out, null, 2) + "\n");
  console.log(`wrote ${ENDPOINTS.length} requests to aureon.postman_collection.json`);

  const automated = buildCollection(ENDPOINTS.filter((e) => !e.manual));
  fs.writeFileSync(path.join(__dirname, "aureon.postman_collection.automated.json"), JSON.stringify(automated, null, 2) + "\n");
  console.log(`wrote ${automated.item.reduce((n: number, f: any) => n + f.item.length, 0)} requests to aureon.postman_collection.automated.json`);
}
